// Generated by cpp11: do not edit by hand
// clang-format off

#include "ramiga_types.h"
#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// ramiga_drives.cpp
void insert_disk_into_df0_(cpp11::external_pointer<VAmiga> amiga, cpp11::external_pointer<DiskImage> image, bool write_protected, int drive_number);
extern "C" SEXP _ramiga_insert_disk_into_df0_(SEXP amiga, SEXP image, SEXP write_protected, SEXP drive_number) {
  BEGIN_CPP11
    insert_disk_into_df0_(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<VAmiga>>>(amiga), cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<DiskImage>>>(image), cpp11::as_cpp<cpp11::decay_t<bool>>(write_protected), cpp11::as_cpp<cpp11::decay_t<int>>(drive_number));
    return R_NilValue;
  END_CPP11
}
// ramiga_drives.cpp
cpp11::external_pointer<DiskImage> floppy_disk_(std::string path);
extern "C" SEXP _ramiga_floppy_disk_(SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(floppy_disk_(cpp11::as_cpp<cpp11::decay_t<std::string>>(path)));
  END_CPP11
}
// test.cpp
cpp11::external_pointer<VAmiga> create_amiga_();
extern "C" SEXP _ramiga_create_amiga_() {
  BEGIN_CPP11
    return cpp11::as_sexp(create_amiga_());
  END_CPP11
}
// test.cpp
SEXP start_amiga_(cpp11::external_pointer<VAmiga> amiga);
extern "C" SEXP _ramiga_start_amiga_(SEXP amiga) {
  BEGIN_CPP11
    return cpp11::as_sexp(start_amiga_(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<VAmiga>>>(amiga)));
  END_CPP11
}
// test.cpp
SEXP load_rom_(cpp11::external_pointer<VAmiga> amiga, std::string path);
extern "C" SEXP _ramiga_load_rom_(SEXP amiga, SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(load_rom_(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<VAmiga>>>(amiga), cpp11::as_cpp<cpp11::decay_t<std::string>>(path)));
  END_CPP11
}
// test.cpp
SEXP load_rom_ext_(cpp11::external_pointer<VAmiga> amiga, std::string path);
extern "C" SEXP _ramiga_load_rom_ext_(SEXP amiga, SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(load_rom_ext_(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<VAmiga>>>(amiga), cpp11::as_cpp<cpp11::decay_t<std::string>>(path)));
  END_CPP11
}
// test.cpp
bool has_rom_(cpp11::external_pointer<VAmiga> amiga);
extern "C" SEXP _ramiga_has_rom_(SEXP amiga) {
  BEGIN_CPP11
    return cpp11::as_sexp(has_rom_(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<VAmiga>>>(amiga)));
  END_CPP11
}
// test.cpp
cpp11::integers get_framebuffer_vport_(cpp11::external_pointer<VAmiga> amiga);
extern "C" SEXP _ramiga_get_framebuffer_vport_(SEXP amiga) {
  BEGIN_CPP11
    return cpp11::as_sexp(get_framebuffer_vport_(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<VAmiga>>>(amiga)));
  END_CPP11
}
// test.cpp
double get_cpu_cycles_(cpp11::external_pointer<VAmiga> amiga);
extern "C" SEXP _ramiga_get_cpu_cycles_(SEXP amiga) {
  BEGIN_CPP11
    return cpp11::as_sexp(get_cpu_cycles_(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<VAmiga>>>(amiga)));
  END_CPP11
}
// test.cpp
cpp11::logicals emulator_info_(cpp11::external_pointer<VAmiga> amiga);
extern "C" SEXP _ramiga_emulator_info_(SEXP amiga) {
  BEGIN_CPP11
    return cpp11::as_sexp(emulator_info_(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<VAmiga>>>(amiga)));
  END_CPP11
}
// test.cpp
void update_screen_(cpp11::external_pointer<VAmiga> amiga);
extern "C" SEXP _ramiga_update_screen_(SEXP amiga) {
  BEGIN_CPP11
    update_screen_(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<VAmiga>>>(amiga));
    return R_NilValue;
  END_CPP11
}
// test.cpp
uint32_t get_cpu_pc_(cpp11::external_pointer<vamiga::VAmiga> amiga);
extern "C" SEXP _ramiga_get_cpu_pc_(SEXP amiga) {
  BEGIN_CPP11
    return cpp11::as_sexp(get_cpu_pc_(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<vamiga::VAmiga>>>(amiga)));
  END_CPP11
}
// test.cpp
void run_until_interrupted_(cpp11::external_pointer<VAmiga> amiga);
extern "C" SEXP _ramiga_run_until_interrupted_(SEXP amiga) {
  BEGIN_CPP11
    run_until_interrupted_(cpp11::as_cpp<cpp11::decay_t<cpp11::external_pointer<VAmiga>>>(amiga));
    return R_NilValue;
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_ramiga_create_amiga_",          (DL_FUNC) &_ramiga_create_amiga_,          0},
    {"_ramiga_emulator_info_",         (DL_FUNC) &_ramiga_emulator_info_,         1},
    {"_ramiga_floppy_disk_",           (DL_FUNC) &_ramiga_floppy_disk_,           1},
    {"_ramiga_get_cpu_cycles_",        (DL_FUNC) &_ramiga_get_cpu_cycles_,        1},
    {"_ramiga_get_cpu_pc_",            (DL_FUNC) &_ramiga_get_cpu_pc_,            1},
    {"_ramiga_get_framebuffer_vport_", (DL_FUNC) &_ramiga_get_framebuffer_vport_, 1},
    {"_ramiga_has_rom_",               (DL_FUNC) &_ramiga_has_rom_,               1},
    {"_ramiga_insert_disk_into_df0_",  (DL_FUNC) &_ramiga_insert_disk_into_df0_,  4},
    {"_ramiga_load_rom_",              (DL_FUNC) &_ramiga_load_rom_,              2},
    {"_ramiga_load_rom_ext_",          (DL_FUNC) &_ramiga_load_rom_ext_,          2},
    {"_ramiga_run_until_interrupted_", (DL_FUNC) &_ramiga_run_until_interrupted_, 1},
    {"_ramiga_start_amiga_",           (DL_FUNC) &_ramiga_start_amiga_,           1},
    {"_ramiga_update_screen_",         (DL_FUNC) &_ramiga_update_screen_,         1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_ramiga(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
