# Generated by cpp11: do not edit by hand

insert_disk_into_ <- function(amiga, image, write_protected, drive_number) {
  invisible(.Call(`_ramiga_insert_disk_into_`, amiga, image, write_protected, drive_number))
}

eject_disk_ <- function(amiga, drive_number, delay) {
  invisible(.Call(`_ramiga_eject_disk_`, amiga, drive_number, delay))
}

disk_image_ <- function(path) {
  .Call(`_ramiga_disk_image_`, path)
}

image_info_ <- function(image) {
  .Call(`_ramiga_image_info_`, image)
}

image_size_ <- function(image) {
  .Call(`_ramiga_image_size_`, image)
}

create_amiga_ <- function() {
  .Call(`_ramiga_create_amiga_`)
}

poweron_amiga_ <- function(amiga) {
  .Call(`_ramiga_poweron_amiga_`, amiga)
}

get_framebuffer_vport_ <- function(amiga) {
  .Call(`_ramiga_get_framebuffer_vport_`, amiga)
}

get_cpu_cycles_ <- function(amiga) {
  .Call(`_ramiga_get_cpu_cycles_`, amiga)
}

emulator_info_ <- function(amiga) {
  .Call(`_ramiga_emulator_info_`, amiga)
}

update_screen_ <- function(amiga) {
  invisible(.Call(`_ramiga_update_screen_`, amiga))
}

get_cpu_pc_ <- function(amiga) {
  .Call(`_ramiga_get_cpu_pc_`, amiga)
}

run_until_interrupted_ <- function(amiga) {
  invisible(.Call(`_ramiga_run_until_interrupted_`, amiga))
}

load_rom_ <- function(amiga, path) {
  .Call(`_ramiga_load_rom_`, amiga, path)
}

load_rom_ext_ <- function(amiga, path) {
  .Call(`_ramiga_load_rom_ext_`, amiga, path)
}

has_rom_ <- function(amiga) {
  .Call(`_ramiga_has_rom_`, amiga)
}
