# Generated by cpp11: do not edit by hand

clear_audio_stream_ <- function(amiga) {
  invisible(.Call(`_ramiga_clear_audio_stream_`, amiga))
}

stereo_audio_buffer_ <- function(amiga) {
  .Call(`_ramiga_stereo_audio_buffer_`, amiga)
}

save_wav_ <- function(amiga, path, sample_rate) {
  invisible(.Call(`_ramiga_save_wav_`, amiga, path, sample_rate))
}

r_list_options_ <- function(component_id, amiga, index) {
  .Call(`_ramiga_r_list_options_`, component_id, amiga, index)
}

r_get_option_ <- function(component_id, amiga, index, key) {
  .Call(`_ramiga_r_get_option_`, component_id, amiga, index, key)
}

r_set_option_ <- function(component_id, amiga, index, key, value) {
  invisible(.Call(`_ramiga_r_set_option_`, component_id, amiga, index, key, value))
}

joystick_ <- function(amiga, port_number) {
  .Call(`_ramiga_joystick_`, amiga, port_number)
}

mouse_ <- function(amiga, port_number) {
  .Call(`_ramiga_mouse_`, amiga, port_number)
}

get_cpu_cycles_ <- function(amiga) {
  .Call(`_ramiga_get_cpu_cycles_`, amiga)
}

get_cpu_pc_ <- function(amiga) {
  .Call(`_ramiga_get_cpu_pc_`, amiga)
}

get_cpu_config_ <- function(amiga) {
  .Call(`_ramiga_get_cpu_config_`, amiga)
}

insert_disk_into_ <- function(amiga, image, write_protected, drive_number) {
  invisible(.Call(`_ramiga_insert_disk_into_`, amiga, image, write_protected, drive_number))
}

eject_disk_ <- function(amiga, drive_number, delay) {
  invisible(.Call(`_ramiga_eject_disk_`, amiga, drive_number, delay))
}

disk_image_ <- function(path) {
  .Call(`_ramiga_disk_image_`, path)
}

fdrive_info_ <- function(amiga, drive_number) {
  .Call(`_ramiga_fdrive_info_`, amiga, drive_number)
}

image_info_ <- function(image) {
  .Call(`_ramiga_image_info_`, image)
}

image_size_ <- function(image) {
  .Call(`_ramiga_image_size_`, image)
}

create_amiga_ <- function() {
  .Call(`_ramiga_create_amiga_`)
}

poweron_amiga_ <- function(amiga) {
  .Call(`_ramiga_poweron_amiga_`, amiga)
}

poweroff_amiga_ <- function(amiga) {
  .Call(`_ramiga_poweroff_amiga_`, amiga)
}

softreset_amiga_ <- function(amiga) {
  .Call(`_ramiga_softreset_amiga_`, amiga)
}

hardreset_amiga_ <- function(amiga) {
  .Call(`_ramiga_hardreset_amiga_`, amiga)
}

emulator_info_ <- function(amiga) {
  .Call(`_ramiga_emulator_info_`, amiga)
}

emulator_config_ <- function(amiga) {
  .Call(`_ramiga_emulator_config_`, amiga)
}

run_until_interrupted_ <- function(amiga) {
  invisible(.Call(`_ramiga_run_until_interrupted_`, amiga))
}

emulator_version_ <- function(amiga) {
  .Call(`_ramiga_emulator_version_`, amiga)
}

emu_set_config_scheme_ <- function(amiga, config_scheme) {
  invisible(.Call(`_ramiga_emu_set_config_scheme_`, amiga, config_scheme))
}

fs_get_traits_ <- function(image) {
  .Call(`_ramiga_fs_get_traits_`, image)
}

fs_describe_ <- function(image) {
  .Call(`_ramiga_fs_describe_`, image)
}

fs_is_formatted_ <- function(image) {
  .Call(`_ramiga_fs_is_formatted_`, image)
}

fs_get_name_ <- function(image) {
  .Call(`_ramiga_fs_get_name_`, image)
}

fs_num_allocated <- function(image) {
  .Call(`_ramiga_fs_num_allocated`, image)
}

load_rom_ <- function(amiga, path) {
  invisible(.Call(`_ramiga_load_rom_`, amiga, path))
}

load_rom_ext_ <- function(amiga, path) {
  invisible(.Call(`_ramiga_load_rom_ext_`, amiga, path))
}

has_rom_ <- function(amiga) {
  .Call(`_ramiga_has_rom_`, amiga)
}

get_rom_traits_ <- function(amiga) {
  .Call(`_ramiga_get_rom_traits_`, amiga)
}

get_mem_config_ <- function(amiga) {
  .Call(`_ramiga_get_mem_config_`, amiga)
}

rgb_to_hex <- function(val) {
  .Call(`_ramiga_rgb_to_hex`, val)
}

get_framebuffer_vport_ <- function(amiga) {
  .Call(`_ramiga_get_framebuffer_vport_`, amiga)
}

update_screen_ <- function(amiga) {
  invisible(.Call(`_ramiga_update_screen_`, amiga))
}

update_scanline_ <- function(amiga) {
  invisible(.Call(`_ramiga_update_scanline_`, amiga))
}

save_framebuffer_ <- function(amiga, path) {
  invisible(.Call(`_ramiga_save_framebuffer_`, amiga, path))
}
