# Generated by cpp11: do not edit by hand

get_cpu_cycles_ <- function(amiga) {
  .Call(`_ramiga_get_cpu_cycles_`, amiga)
}

get_cpu_pc_ <- function(amiga) {
  .Call(`_ramiga_get_cpu_pc_`, amiga)
}

get_cpu_config_ <- function(amiga) {
  .Call(`_ramiga_get_cpu_config_`, amiga)
}

insert_disk_into_ <- function(amiga, image, write_protected, drive_number) {
  invisible(.Call(`_ramiga_insert_disk_into_`, amiga, image, write_protected, drive_number))
}

eject_disk_ <- function(amiga, drive_number, delay) {
  invisible(.Call(`_ramiga_eject_disk_`, amiga, drive_number, delay))
}

disk_image_ <- function(path) {
  .Call(`_ramiga_disk_image_`, path)
}

fdrive_info_ <- function(amiga, drive_number) {
  .Call(`_ramiga_fdrive_info_`, amiga, drive_number)
}

image_info_ <- function(image) {
  .Call(`_ramiga_image_info_`, image)
}

image_size_ <- function(image) {
  .Call(`_ramiga_image_size_`, image)
}

create_amiga_ <- function() {
  .Call(`_ramiga_create_amiga_`)
}

poweron_amiga_ <- function(amiga) {
  .Call(`_ramiga_poweron_amiga_`, amiga)
}

poweroff_amiga_ <- function(amiga) {
  .Call(`_ramiga_poweroff_amiga_`, amiga)
}

softreset_amiga_ <- function(amiga) {
  .Call(`_ramiga_softreset_amiga_`, amiga)
}

emulator_info_ <- function(amiga) {
  .Call(`_ramiga_emulator_info_`, amiga)
}

run_until_interrupted_ <- function(amiga) {
  invisible(.Call(`_ramiga_run_until_interrupted_`, amiga))
}

test_fs_ <- function(image) {
  invisible(.Call(`_ramiga_test_fs_`, image))
}

fs_get_traits_ <- function(image) {
  .Call(`_ramiga_fs_get_traits_`, image)
}

fs_describe_ <- function(image) {
  .Call(`_ramiga_fs_describe_`, image)
}

fs_is_formatted_ <- function(image) {
  .Call(`_ramiga_fs_is_formatted_`, image)
}

fs_get_name_ <- function(image) {
  .Call(`_ramiga_fs_get_name_`, image)
}

fs_num_allocated <- function(image) {
  .Call(`_ramiga_fs_num_allocated`, image)
}

load_rom_ <- function(amiga, path) {
  invisible(.Call(`_ramiga_load_rom_`, amiga, path))
}

load_rom_ext_ <- function(amiga, path) {
  invisible(.Call(`_ramiga_load_rom_ext_`, amiga, path))
}

has_rom_ <- function(amiga) {
  .Call(`_ramiga_has_rom_`, amiga)
}

get_rom_traits_ <- function(amiga) {
  .Call(`_ramiga_get_rom_traits_`, amiga)
}

get_mem_config_ <- function(amiga) {
  .Call(`_ramiga_get_mem_config_`, amiga)
}

get_framebuffer_vport_ <- function(amiga) {
  .Call(`_ramiga_get_framebuffer_vport_`, amiga)
}

update_screen_ <- function(amiga) {
  invisible(.Call(`_ramiga_update_screen_`, amiga))
}

update_scanline_ <- function(amiga) {
  invisible(.Call(`_ramiga_update_scanline_`, amiga))
}
